const employmentTypeList = '''[
  "Full Time",
  "Part Time",
  "Internship",
  "Volunteer",
  "Any Type"
]''';

const educationRequireList = '''[
  "None",
  "High School",
  "Associate",
  "Bachelor",
  "Master",
  "Doctor"
]''';

const experienceRequireList = '''[
  "None",
  "1 Year",
  "2 Years",
  "3 Years",
  "4 Years",
  "5 Years",
  "> 5 Years"
]''';

//TODO: finish this
const salaryRageList = '''[
    {
    "None": [
    ""
    ],
    "<1k": [
    ""
    ],
    "1k": [
        "1.5k",
        "2k",
        "2.5k",
        "3k",
        "3.5k"
    ],
    "1.5k": [
        "2k",
        "2.5k",
        "3k",
        "3.5k",
        "4k"
    ],
    "2k": [
        "2.5k",
        "3k",
        "3.5k",
        "4k",
        "4.5k"
    ],
    "2.5k": [
        "3k",
        "3.5k",
        "4k",
        "4.5k",
        "5k"
    ],
    "3.5k": [
        "4k",
        "4.5k",
        "5k",
        "5.5k",
        "6k"
    ],
    "4k": [
        "4.5k",
        "5k",
        "5.5k",
        "6k",
        "6.5k"
    ],
    "4.5k": [
        "5k",
        "5.5k",
        "6k",
        "6.5k",
        "7k"
    ],
    "5k": [
        "5.5k",
        "6k",
        "6.5k",
        "7k",
        "7.5k"
    ],
    ">7.5k": [
    ""
    ]
}
]''';

const jobTitleCategoriesList = '''[
    {
    "Accounting and Auditing": [
"Account Manager",
"Accountant",
"Accounting",
"Accounting Assistant",
"Accounting Clerk",
"Accounting Specialist",
"Accounting Technician",
"Analyst",
"Assessor",
"Auditing",
"Auditor",
"Bookkeeper",
"Business Analyst",
"CFO",
"Controller",
"Estimator",
"Finance Manager",
"Financial Analyst",
"Fraud Analyst",
"Investment Analyst",
"Loan Officer",
"Project Accountant",
"Project Manager",
"Property Accountant",
"Quality Manager",
"Sales Manager",
"Staff Accountant",
"Tax Accountant",
"Tax Associate"
    ],
    "Banking and Insurance": [
        "Analyst",
"Appraiser",
"Auditor",
"Bank Manager",
"Bank Teller",
"Banker",
"Banking",
"Bookkeeper",
"Broker",
"Budget Analyst",
"Business Analyst",
"CFO",
"Claims Adjuster",
"Claims Examiner",
"Claims Specialist",
"Coordinator",
"Credit Analyst",
"Equity Analyst",
"Escrow Assistant",
"Executive Assistant",
"General Manager",
"Insurance",
"Insurance Agent",
"Investment Advisor",
"Investment Analyst",
"Loan Officer",
"Loan Originator",
"Loan Processor",
"Loss Prevention Manager",
"Mortgage Closer",
"Mortgage Loan Officer",
"Mortgage Loan Originator",
"Mortgage Processor",
"Mortgage Underwriter",
"Operations Manager",
"Personal Banker",
"Risk Manager",
"Security Guard",
"Supervisor",
"Tax Preparer",
"Teller",
"Trader",
"Trading Analyst",
"Treasury"
    ],
    "Finance": [
        "Account Manager",
"Accountant",
"Accounts Payable Clerk",
"Administrative Assistant",
"Analyst",
"Billing Clerk",
"Billing Specialist",
"Bookkeeper",
"Cashier",
"CFO",
"Collections Specialist",
"Compliance Specialist",
"Content Analyst",
"Controller",
"Debt Collector",
"Finance",
"Finance Analyst",
"Finance Manager",
"Financial",
"Financial Advisor",
"Financial Analyst",
"Financial Consultant",
"Financial Controller",
"Financial Counselor",
"Financial Manager",
"Financial Planner",
"Inventory Analyst",
"Investment Analyst",
"Payroll Assistant",
"Payroll Clerk",
"Payroll Specialist",
"Project Analyst",
"Purchasing Agent",
"Purchasing Assistant",
"Quantitative Analyst",
"Reporting Analyst",
"Risk Analyst",
"Statistical Analyst",
"Tax Analyst",
"Treasury Analyst",
"Underwriter"
    ],
    "Agriculture and agribusiness": [
        "Agriculture",
"Analyst",
"Dispatcher",
"Farm",
"Farmer",
"Gardener",
"General Laborer",
"Janitor",
"Machinist",
"Mechanic",
"Packer",
"Picker",
"Quality Engineer",
"Sales Representative",
"Sorter",
"Stable Hand",
"Veterinary"
    ],
    "Animal Care": [
       "Animal Care",
"Animal Technician",
"Caretaker",
"Farm Manager",
"Pest Control Technician",
"Veterinarian",
"Veterinary Technician"
    ],
    "Architecture": [
        "3d Designer",
"Architect",
"Architectural Designer",
"Architecture",
"Artist",
"Designer",
"Estimator",
"Planner",
"Footer"
    ],
    "Construction": [
        "Assistant Superintendent",
"Building Inspector",
"Carpenter",
"Construction",
"Construction Foreman",
"Construction Helper",
"Construction Inspector",
"Construction Laborer",
"Construction Supervisor",
"Construction Worker",
"Coordinator",
"Crane Operator",
"Electrical Apprentice",
"Electrical Engineer",
"Electrical Helper",
"Electrical Inspector",
"Electrical Superintendent",
"Electrician",
"Electronics",
"Equipment Operator",
"Field Inspector",
"Fitter",
"Foreman",
"Handyman",
"Home Builder",
"Home Inspector",
"Industrial Electrician",
"Installer",
"Janitor",
"Journeyman Electrician",
"Locksmith",
"Machinist",
"Maintenance",
"Maintenance Electrician",
"Mason",
"Master Electrician",
"Operations Supervisor",
"Painter",
"Plumber",
"Process Engineer",
"Quality Engineer",
"Repair",
"Sheet Metal Mechanic",
"Welder"
    ],
    "Design And Creativity": [
        "Architect",
"Art Director",
"Artist",
"Coder",
"Content Producer",
"Creative",
"Design",
"Designer",
"Editor",
"Front End Developer",
"Graphic Artist",
"Graphic Designer",
"Illustrator",
"Industrial Designer",
"Interior Designer",
"Junior Designer",
"Production Designer",
"Tailor",
"Technical Writer",
"User Experience Designer",
"Video Producer",
"Visual Designer",
"Web Designer"
    ],
    "Real Estate": [
        "Architect",
"Assistant Property Manager",
"Facility Manager",
"Handyman",
"Land Surveyor",
"Lawyer",
"Leasing Agent",
"Leasing Consultant",
"Property Manager",
"Real Estate",
"Real Estate Agent",
"Real Estate Analyst",
"Real Estate Appraiser",
"Real Estate Assistant",
"Realtor"
    ],
    "Human Resources": [
    "Benefits Analyst",
"Benefits Coordinator",
"Benefits Specialist",
"Career Coach",
"Career Counselor",
"Director Of Human Resources",
"Executive Recruiter",
"HR Analyst",
"HR Assistant",
"HR Business Partner",
"HR Consultant",
"HR Coordinator",
"HR Director",
"HR Generalist",
"HR Manager",
"HR Recruiter",
"HR Specialist",
"Human Resource Development",
"Human Resources",
"Job Coach",
"Recruiter",
"Recruiting Coordinator",
"Recruitment Manager",
"Staffing Coordinator",
"Technical Recruiter"
    ],
    "Marketing, Advertising and PR": [
    "Account Manager",
"Advertising",
"Art Director",
"Assistant Store Manager",
"Brand Manager",
"Business Analyst",
"Business Development Director",
"Campaign Manager",
"Category Manager",
"Channel Manager",
"Chief Marketing Officer",
"CMO",
"Communications Manager",
"Community Manager",
"Content Editor",
"Content Manager",
"Content Specialist",
"Coordinator",
"Copywriter",
"Creative Director",
"Digital Marketing",
"Director Of Marketing",
"Editor",
"Engagement Manager",
"Event Manager",
"Illustrator",
"Interviewer",
"Market Research Analyst",
"Marketing",
"Marketing Analyst",
"Marketing Assistant",
"Marketing Associate",
"Marketing Coordinator",
"Marketing Director",
"Marketing Executive",
"Marketing Manager",
"Marketing Specialist",
"Media Buyer",
"Media Director",
"Media Planner",
"Merchandiser",
"Office Manager",
"Operations Manager",
"Personal Assistant",
"PR",
"Product Marketing Manager",
"Product Owner",
"Regional Manager",
"Social Media Manager",
"Strategy Manager",
"Territory Manager",
"UI Designer",
"Web Designer",
"Writer"
    ],
    "Administration": [
    "Account Manager",
"Admin",
"Administration",
"Administrative",
"Administrative Assistant",
"Administrative Coordinator",
"Administrator",
"Analyst",
"Assistant",
"Business Analyst",
"Cashier",
"Claims Processor",
"Claims Representative",
"Clerical Assistant",
"Clerk",
"Concierge",
"Contract Manager",
"Contract Specialist",
"Contracts Administrator",
"Coordinator",
"Customer Service Supervisor",
"Data Entry",
"Data Entry Clerk",
"Data Entry Operator",
"Dispatcher",
"Drafter",
"Event Coordinator",
"Executive Administrative Assistant",
"Executive Assistant",
"File Clerk",
"Financial Assistant",
"Front Desk Clerk",
"Hostess",
"Mail Clerk",
"Medical Administrative Assistant",
"Medical Secretary",
"Network Administrator",
"Office Administrator",
"Office Assistant",
"Office Clerk",
"Office Coordinator",
"Office Manager",
"Patient Coordinator",
"Payroll Administrator",
"Personal Assistant",
"Portfolio Manager",
"Project Assistant",
"Ramp Agent",
"Receptionist",
"Sales Representative",
"School Secretary",
"Secretary",
"Security Guard",
"Service Advisor",
"Sharepoint",
"Signing Agent",
"Surveyor",
"Switchboard Operator",
"System Administrator",
"Typist",
"Underwriting Assistant"
    ],
    "Assistants": [
    "Accounting Assistant",
"Administrative Assistant",
"Aide",
"Assistant",
"Assistant Manager",
"Assistant Teacher",
"Certified Medical Assistant",
"Certified Occupational Therapy Assistant",
"Chiropractic Assistant",
"CNA",
"Dental Assistant",
"Executive Assistant",
"Graduate Assistant",
"HR Assistant",
"Lab Assistant",
"Laboratory Assistant",
"Legal Assistant",
"Marketing Assistant",
"Medical Administrative Assistant",
"Medical Assistant",
"Nursing Assistant",
"Occupational Therapy Assistant",
"Office Assistant",
"Personal Assistant",
"Physical Therapist Assistant",
"Physician Assistant",
"Production Assistant",
"Program Assistant",
"Real Estate Assistant",
"Research Assistant",
"Teacher Assistant",
"Teaching Assistant"
    ],
    "Business Specialists": [
    "Assistant Buyer",
"Assistant Controller",
"Business",
"Business development",
"Business Process Analyst",
"Compensation Analyst",
"Compliance Analyst",
"Construction Estimator",
"Contract Analyst",
"Cost Estimator",
"Electrical Estimator",
"Employment Specialist",
"Energy Analyst",
"Entry Level Sales",
"Environmental Manager",
"Event Director",
"Facilitator",
"Field Investigator",
"General Labor",
"Healthcare Analyst",
"Insurance Adjuster",
"International Business",
"Merchandise Planner",
"Negotiator",
"Operations Analyst",
"Operations Coordinator",
"Operations Specialist",
"Planning",
"Policy Analyst",
"Pricing Analyst",
"Product Analyst",
"Product Specialist",
"Program Coordinator",
"Property Adjuster",
"Quality Control",
"Sales Trainer",
"Services Manager",
"Sports Business",
"Strategic Planner",
"Strategy"
    ],
    "Consultancy": [
    "Business Consultant",
"Consultant",
"Energy Consultant",
"Healthcare Consultant",
"Implementation Consultant",
"Marketing Consultant",
"Sap Consultant",
"Solutions Consultant",
"Strategic Consultant"
    ],
    "Legal": [
    "Attorney",
"City Attorney",
"Clerk",
"Compliance Counsel",
"Content Manager",
"Contract Attorney",
"Corporate Attorney",
"Corporate Counsel",
"Corporate Lawyer",
"Corporate Paralegal",
"Counsel",
"Estate Planning Attorney",
"General Counsel",
"Healthcare Attorney",
"International Lawyer",
"Judge",
"Law Assistant",
"Law Clerk",
"Lawyer",
"Legal",
"Legal Analyst",
"Legal Assistant",
"Legal Clerk",
"Legal Consultant",
"Legal Counsel",
"Legal Secretary",
"Notary Public",
"Paralegal",
"Real Estate Attorney",
"Tax Attorney",
"Tax Counsel",
"Title Clerk"
    ],
    "Secretarial, Clerical and Administrative Assistant": [
    "Administrative Assistant",
"Call Center",
"Call Center Representative",
"Clerical",
"Clerk",
"Concierge",
"Customer Service Manager",
"Customer Service Representative",
"Executive Assistant",
"Field Service Technician",
"Help Desk Analyst",
"Help Desk Technician",
"Hostess",
"HR Assistant",
"Legal Assistant",
"Personal Assistant",
"Receptionist",
"Secretarial",
"Secretary",
"Service Manager",
"Service Technician"
    ],
    "Service": [
    "Activities Assistant",
"Activities Director",
"Admissions Coordinator",
"Admissions Counselor",
"Admissions Representative",
"Analyst",
"Application Analyst",
"Background Investigator",
"Behavior Analyst",
"Behavior Specialist",
"Chaplain",
"Child Care Worker",
"Clinical Social Worker",
"Clinical Supervisor",
"College Counselor",
"Community Health Worker",
"Community Liaison",
"Crisis Counselor",
"Customer Service",
"Customer Service Manager",
"Customer Service Representative",
"Desktop Support",
"Desktop Support Technician",
"Direct Support Professional",
"Discharge Planner",
"Education Consultant",
"Education Director",
"Education Specialist",
"Field Engineer",
"Field Service Engineer",
"Field Service Technician",
"Field Technician",
"Fraud Investigator",
"Health Coordinator",
"Healthcare Social Worker",
"Help Desk Analyst",
"Help Desk Technician",
"Hospice Social Worker",
"Intake Coordinator",
"Licensed Clinical Social Worker",
"Life Coach",
"Medical Social Worker",
"Mentor",
"Patient Service Representative",
"Peer Support Specialist",
"Private Investigator",
"Program Assistant",
"Public Health Analyst",
"Referral Coordinator",
"Relationship Manager",
"Resident Assistant",
"Residential Aide",
"Residential Counselor",
"Room Attendant",
"Sales Engineer",
"Sanitation Worker",
"School Counselor",
"School Social Worker",
"Service Manager",
"Service Technician",
"Social Services",
"Social Services Assistant",
"Spa Manager",
"Spiritual Director",
"Student Advisor",
"Substance Abuse Counselor",
"Transportation Security Officer",
"Union Organizer",
"Union Representative",
"Volunteer Coordinator",
"Youth Counselor"
    ],
    "t": [
    ],
    "t": [
    ],
    "t": [
    ],
    "t": [
    ],
    "t": [
    ],
    "t": [
    ]
    
}
]''';

const usStatesCitiesList = '''[
    {
    "Alabama": [
        "Auburn",
        "Birmingham",
        "Decatur",
        "Dothan",
        "Florence",
        "Gadsden",
        "Hoover",
        "Huntsville",
        "Madison",
        "Mobile",
        "Montgomery",
        "Tuscaloosa"
    ],
    "Alaska": [
        "Anchorage"
    ],
    "Arizona": [
        "Apache Junction",
        "Avondale",
        "Buckeye",
        "Bullhead City",
        "Casa Grande",
        "Chandler",
        "Flagstaff",
        "Gilbert",
        "Glendale",
        "Goodyear",
        "Lake Havasu City",
        "Marana",
        "Maricopa",
        "Mesa",
        "Oro Valley",
        "Peoria",
        "Phoenix",
        "Prescott Valley",
        "Prescott",
        "Scottsdale",
        "Sierra Vista",
        "Surprise",
        "Tempe",
        "Tucson",
        "Yuma"
    ],
    "Arkansas": [
        "Bentonville",
        "Conway",
        "Fayetteville",
        "Fort Smith",
        "Jonesboro",
        "Little Rock",
        "North Little Rock",
        "Pine Bluff",
        "Rogers",
        "Springdale"
    ],
    "California": [
        "Alameda",
        "Alhambra",
        "Aliso Viejo",
        "Anaheim",
        "Antioch",
        "Apple Valley",
        "Arcadia",
        "Azusa",
        "Bakersfield",
        "Baldwin Park",
        "Beaumont",
        "Bell Gardens",
        "Bellflower",
        "Berkeley",
        "Brea",
        "Brentwood",
        "Buena Park",
        "Burbank",
        "Calexico",
        "Camarillo",
        "Campbell",
        "Carlsbad",
        "Carson",
        "Cathedral City",
        "Ceres",
        "Cerritos",
        "Chico",
        "Chino Hills",
        "Chino",
        "Chula Vista",
        "Citrus Heights",
        "Clovis",
        "Coachella",
        "Colton",
        "Compton",
        "Concord",
        "Corona",
        "Costa Mesa",
        "Covina",
        "Culver City",
        "Cupertino",
        "Cypress",
        "Daly City",
        "Danville",
        "Davis",
        "Delano",
        "Diamond Bar",
        "Downey",
        "Dublin",
        "Eastvale",
        "El Cajon",
        "El Centro",
        "El Monte",
        "Elk Grove",
        "Encinitas",
        "Escondido",
        "Fairfield",
        "Folsom",
        "Fontana",
        "Fountain Valley",
        "Fremont",
        "Fresno",
        "Fullerton",
        "Garden Grove",
        "Gardena",
        "Gilroy",
        "Glendale",
        "Glendora",
        "Hanford",
        "Hawthorne",
        "Hayward",
        "Hemet",
        "Hesperia",
        "Highland",
        "Huntington Beach",
        "Huntington Park",
        "Indio",
        "Inglewood",
        "Irvine",
        "Jurupa Valley",
        "La Habra",
        "La Mesa",
        "La Mirada",
        "La Puente",
        "La Quinta",
        "Laguna Niguel",
        "Lake Elsinore",
        "Lake Forest",
        "Lakewood",
        "Lancaster",
        "Lincoln",
        "Livermore",
        "Lodi",
        "Lompoc",
        "Long Beach",
        "Los Angeles",
        "Los Banos",
        "Lynwood",
        "Madera",
        "Manteca",
        "Martinez",
        "Menifee",
        "Merced",
        "Milpitas",
        "Mission Viejo",
        "Modesto",
        "Monrovia",
        "Montclair",
        "Montebello",
        "Monterey Park",
        "Moreno Valley",
        "Morgan Hill",
        "Mountain View",
        "Murrieta",
        "Napa",
        "National City",
        "Newark",
        "Newport Beach",
        "Norwalk",
        "Novato",
        "Oakland",
        "Oakley",
        "Oceanside",
        "Ontario",
        "Orange",
        "Oxnard",
        "Pacifica",
        "Palm Desert",
        "Palm Springs",
        "Palmdale",
        "Palo Alto",
        "Paramount",
        "Pasadena",
        "Perris",
        "Petaluma",
        "Pico Rivera",
        "Pittsburg",
        "Placentia",
        "Pleasanton",
        "Pomona",
        "Porterville",
        "Poway",
        "Rancho Cordova",
        "Rancho Cucamonga",
        "Rancho Palos Verdes",
        "Rancho Santa Margarita",
        "Redding",
        "Redlands",
        "Redondo Beach",
        "Redwood City",
        "Rialto",
        "Richmond",
        "Riverside",
        "Rocklin",
        "Rohnert Park",
        "Rosemead",
        "Roseville",
        "Sacramento",
        "Salinas",
        "San Bernardino",
        "San Bruno",
        "San Buenaventura (Ventura)",
        "San Clemente",
        "San Diego",
        "San Francisco",
        "San Gabriel",
        "San Jacinto",
        "San Jose",
        "San Leandro",
        "San Luis Obispo",
        "San Marcos",
        "San Mateo",
        "San Rafael",
        "San Ramon",
        "Santa Ana",
        "Santa Barbara",
        "Santa Clara",
        "Santa Clarita",
        "Santa Cruz",
        "Santa Maria",
        "Santa Monica",
        "Santa Rosa",
        "Santee",
        "Simi Valley",
        "South Gate",
        "South San Francisco",
        "Stanton",
        "Stockton",
        "Sunnyvale",
        "Temecula",
        "Thousand Oaks",
        "Torrance",
        "Tracy",
        "Tulare",
        "Turlock",
        "Tustin",
        "Union City",
        "Upland",
        "Vacaville",
        "Vallejo",
        "Victorville",
        "Visalia",
        "Vista",
        "Walnut Creek",
        "Watsonville",
        "West Covina",
        "West Sacramento",
        "Westminster",
        "Whittier",
        "Woodland",
        "Yorba Linda",
        "Yuba City",
        "Yucaipa"
    ],
    "Colorado": [
        "Arvada",
        "Aurora",
        "Boulder",
        "Broomfield",
        "Castle Rock",
        "Centennial",
        "Colorado Springs",
        "Commerce City",
        "Denver",
        "Fort Collins",
        "Grand Junction",
        "Greeley",
        "Lakewood",
        "Littleton",
        "Longmont",
        "Loveland",
        "Northglenn",
        "Parker",
        "Pueblo",
        "Thornton",
        "Westminster"
    ],
    "Connecticut": [
        "Bridgeport",
        "Bristol",
        "Danbury",
        "Hartford",
        "Meriden",
        "Middletown",
        "Milford",
        "New Britain",
        "New Haven",
        "Norwalk",
        "Norwich",
        "Shelton",
        "Stamford",
        "Waterbury",
        "West Haven"
    ],
    "Delaware": [
        "Dover",
        "Wilmington"
    ],
    "District of Columbia": [
        "Washington"
    ],
    "Florida": [
        "Altamonte Springs",
        "Apopka",
        "Aventura",
        "Boca Raton",
        "Bonita Springs",
        "Boynton Beach",
        "Bradenton",
        "Cape Coral",
        "Clearwater",
        "Coconut Creek",
        "Coral Gables",
        "Coral Springs",
        "Cutler Bay",
        "Davie",
        "Daytona Beach",
        "Deerfield Beach",
        "Delray Beach",
        "Deltona",
        "Doral",
        "Fort Lauderdale",
        "Fort Myers",
        "Fort Pierce",
        "Gainesville",
        "Greenacres",
        "Hallandale Beach",
        "Hialeah",
        "Hollywood",
        "Homestead",
        "Jacksonville",
        "Jupiter",
        "Kissimmee",
        "Lakeland",
        "Largo",
        "Lauderhill",
        "Margate",
        "Melbourne",
        "Miami Beach",
        "Miami Gardens",
        "Miami",
        "Miramar",
        "North Lauderdale",
        "North Miami Beach",
        "North Miami",
        "North Port",
        "Oakland Park",
        "Ocala",
        "Ocoee",
        "Orlando",
        "Ormond Beach",
        "Palm Bay",
        "Palm Beach Gardens",
        "Palm Coast",
        "Pembroke Pines",
        "Pensacola",
        "Pinellas Park",
        "Plantation",
        "Pompano Beach",
        "Port Orange",
        "Port St. Lucie",
        "Sanford",
        "Sarasota",
        "St. Cloud",
        "St. Petersburg",
        "Sunrise",
        "Tallahassee",
        "Tamarac",
        "Tampa",
        "Titusville",
        "Wellington",
        "West Palm Beach",
        "Weston",
        "Winter Garden"
    ],
    "Georgia": [
        "Albany",
        "Alpharetta",
        "Athens-Clarke County",
        "Atlanta",
        "Augusta-Richmond County",
        "Columbus",
        "Dunwoody",
        "Johns Creek",
        "Macon",
        "Marietta",
        "Roswell",
        "Sandy Springs",
        "Savannah",
        "Smyrna",
        "Valdosta",
        "Warner Robins"
    ],
    "Hawaii": [
        "Honolulu"
    ],
    "Idaho": [
        "Boise City",
        "Caldwell",
        "Coeur d'Alene",
        "Idaho Falls",
        "Meridian",
        "Nampa",
        "Pocatello",
        "Twin Falls"
    ],
    "Illinois": [
        "Addison",
        "Arlington Heights",
        "Aurora",
        "Bartlett",
        "Belleville",
        "Berwyn",
        "Bloomington",
        "Bolingbrook",
        "Buffalo Grove",
        "Calumet City",
        "Carol Stream",
        "Carpentersville",
        "Champaign",
        "Chicago",
        "Cicero",
        "Crystal Lake",
        "DeKalb",
        "Decatur",
        "Des Plaines",
        "Downers Grove",
        "Elgin",
        "Elmhurst",
        "Evanston",
        "Glenview",
        "Hanover Park",
        "Hoffman Estates",
        "Joliet",
        "Lombard",
        "Moline",
        "Mount Prospect",
        "Naperville",
        "Normal",
        "Oak Lawn",
        "Oak Park",
        "Orland Park",
        "Palatine",
        "Park Ridge",
        "Peoria",
        "Plainfield",
        "Quincy",
        "Rock Island",
        "Rockford",
        "Romeoville",
        "Schaumburg",
        "Skokie",
        "Springfield",
        "Streamwood",
        "Tinley Park",
        "Urbana",
        "Waukegan",
        "Wheaton",
        "Wheeling"
    ],
    "Indiana": [
        "Anderson",
        "Bloomington",
        "Carmel",
        "Columbus",
        "Elkhart",
        "Evansville",
        "Fishers",
        "Fort Wayne",
        "Gary",
        "Greenwood",
        "Hammond",
        "Indianapolis",
        "Jeffersonville",
        "Kokomo",
        "Lafayette",
        "Lawrence",
        "Mishawaka",
        "Muncie",
        "Noblesville",
        "Portage",
        "South Bend",
        "Terre Haute"
    ],
    "Iowa": [
        "Ames",
        "Ankeny",
        "Cedar Falls",
        "Cedar Rapids",
        "Council Bluffs",
        "Davenport",
        "Des Moines",
        "Dubuque",
        "Iowa City",
        "Sioux City",
        "Urbandale",
        "Waterloo",
        "West Des Moines"
    ],
    "Kansas": [
        "Hutchinson",
        "Kansas City",
        "Lawrence",
        "Lenexa",
        "Manhattan",
        "Olathe",
        "Overland Park",
        "Salina",
        "Shawnee",
        "Topeka",
        "Wichita"
    ],
    "Kentucky": [
        "Bowling Green",
        "Covington",
        "Lexington-Fayette",
        "Louisville/Jefferson County",
        "Owensboro"
    ],
    "Louisiana": [
        "Alexandria",
        "Baton Rouge",
        "Bossier City",
        "Kenner",
        "Lafayette",
        "Lake Charles",
        "Monroe",
        "New Orleans",
        "Shreveport"
    ],
    "Maine": [
        "Portland"
    ],
    "Maryland": [
        "Annapolis",
        "Baltimore",
        "Bowie",
        "Frederick",
        "Gaithersburg",
        "Hagerstown",
        "Rockville"
    ],
    "Massachusetts": [
        "Attleboro",
        "Barnstable Town",
        "Beverly",
        "Boston",
        "Brockton",
        "Cambridge",
        "Chelsea",
        "Chicopee",
        "Everett",
        "Fall River",
        "Fitchburg",
        "Haverhill",
        "Holyoke",
        "Lawrence",
        "Leominster",
        "Lowell",
        "Lynn",
        "Malden",
        "Marlborough",
        "Medford",
        "Methuen",
        "New Bedford",
        "Newton",
        "Peabody",
        "Pittsfield",
        "Quincy",
        "Revere",
        "Salem",
        "Somerville",
        "Springfield",
        "Taunton",
        "Waltham",
        "Westfield",
        "Weymouth Town",
        "Woburn",
        "Worcester"
    ],
    "Michigan": [
        "Ann Arbor",
        "Battle Creek",
        "Dearborn Heights",
        "Dearborn",
        "Detroit",
        "East Lansing",
        "Farmington Hills",
        "Flint",
        "Grand Rapids",
        "Kalamazoo",
        "Kentwood",
        "Lansing",
        "Lincoln Park",
        "Livonia",
        "Midland",
        "Muskegon",
        "Novi",
        "Pontiac",
        "Portage",
        "Rochester Hills",
        "Roseville",
        "Royal Oak",
        "Saginaw",
        "Southfield",
        "St. Clair Shores",
        "Sterling Heights",
        "Taylor",
        "Troy",
        "Warren",
        "Westland",
        "Wyoming"
    ],
    "Minnesota": [
        "Apple Valley",
        "Blaine",
        "Bloomington",
        "Brooklyn Park",
        "Burnsville",
        "Coon Rapids",
        "Duluth",
        "Eagan",
        "Eden Prairie",
        "Edina",
        "Lakeville",
        "Mankato",
        "Maple Grove",
        "Maplewood",
        "Minneapolis",
        "Minnetonka",
        "Moorhead",
        "Plymouth",
        "Rochester",
        "Shakopee",
        "St. Cloud",
        "St. Louis Park",
        "St. Paul",
        "Woodbury"
    ],
    "Mississippi": [
        "Biloxi",
        "Gulfport",
        "Hattiesburg",
        "Jackson",
        "Meridian",
        "Southaven"
    ],
    "Missouri": [
        "Blue Springs",
        "Cape Girardeau",
        "Chesterfield",
        "Columbia",
        "Florissant",
        "Independence",
        "Jefferson City",
        "Joplin",
        "Kansas City",
        "Lee's Summit",
        "O'Fallon",
        "Springfield",
        "St. Charles",
        "St. Joseph",
        "St. Louis",
        "St. Peters"
    ],
    "Montana": [
        "Billings",
        "Bozeman",
        "Great Falls",
        "Missoula"
    ],
    "Nebraska": [
        "Bellevue",
        "Grand Island",
        "Lincoln",
        "Omaha"
    ],
    "Nevada": [
        "Carson City",
        "Henderson",
        "Las Vegas",
        "North Las Vegas",
        "Reno",
        "Sparks"
    ],
    "New Hampshire": [
        "Concord",
        "Manchester",
        "Nashua"
    ],
    "New Jersey": [
        "Atlantic City",
        "Bayonne",
        "Camden",
        "Clifton",
        "East Orange",
        "Elizabeth",
        "Hackensack",
        "Hoboken",
        "Jersey City",
        "Kearny",
        "Linden",
        "New Brunswick",
        "Newark",
        "Passaic",
        "Paterson",
        "Perth Amboy",
        "Plainfield",
        "Sayreville",
        "Trenton",
        "Union City",
        "Vineland",
        "West New York"
    ],
    "New Mexico": [
        "Albuquerque",
        "Clovis",
        "Farmington",
        "Las Cruces",
        "Rio Rancho",
        "Roswell",
        "Santa Fe"
    ],
    "New York": [
        "Albany",
        "Binghamton",
        "Buffalo",
        "Freeport",
        "Hempstead",
        "Mount Vernon",
        "New Rochelle",
        "New York",
        "Niagara Falls",
        "Rochester",
        "Schenectady",
        "Syracuse",
        "Troy",
        "Utica",
        "Valley Stream",
        "White Plains",
        "Yonkers"
    ],
    "North Carolina": [
        "Apex",
        "Asheville",
        "Burlington",
        "Cary",
        "Chapel Hill",
        "Charlotte",
        "Concord",
        "Durham",
        "Fayetteville",
        "Gastonia",
        "Goldsboro",
        "Greensboro",
        "Greenville",
        "Hickory",
        "High Point",
        "Huntersville",
        "Jacksonville",
        "Kannapolis",
        "Raleigh",
        "Rocky Mount",
        "Wilmington",
        "Wilson",
        "Winston-Salem"
    ],
    "North Dakota": [
        "Bismarck",
        "Fargo",
        "Grand Forks",
        "Minot"
    ],
    "Ohio": [
        "Akron",
        "Beavercreek",
        "Canton",
        "Cincinnati",
        "Cleveland Heights",
        "Cleveland",
        "Columbus",
        "Cuyahoga Falls",
        "Dayton",
        "Dublin",
        "Elyria",
        "Euclid",
        "Fairfield",
        "Findlay",
        "Grove City",
        "Hamilton",
        "Huber Heights",
        "Kettering",
        "Lakewood",
        "Lancaster",
        "Lima",
        "Lorain",
        "Mansfield",
        "Marion",
        "Mentor",
        "Middletown",
        "Newark",
        "Parma",
        "Springfield",
        "Strongsville",
        "Toledo",
        "Warren",
        "Westerville",
        "Youngstown"
    ],
    "Oklahoma": [
        "Broken Arrow",
        "Edmond",
        "Enid",
        "Lawton",
        "Midwest City",
        "Moore",
        "Muskogee",
        "Norman",
        "Oklahoma City",
        "Stillwater",
        "Tulsa"
    ],
    "Oregon": [
        "Albany",
        "Beaverton",
        "Bend",
        "Corvallis",
        "Eugene",
        "Gresham",
        "Hillsboro",
        "Keizer",
        "Lake Oswego",
        "Medford",
        "Portland",
        "Salem",
        "Springfield",
        "Tigard"
    ],
    "Pennsylvania": [
        "Allentown",
        "Altoona",
        "Bethlehem",
        "Erie",
        "Harrisburg",
        "Lancaster",
        "Philadelphia",
        "Pittsburgh",
        "Reading",
        "Scranton",
        "State College",
        "Wilkes-Barre",
        "York"
    ],
    "Rhode Island": [
        "Cranston",
        "East Providence",
        "Pawtucket",
        "Providence",
        "Warwick",
        "Woonsocket"
    ],
    "South Carolina": [
        "Charleston",
        "Columbia",
        "Florence",
        "Goose Creek",
        "Greenville",
        "Hilton Head Island",
        "Mount Pleasant",
        "North Charleston",
        "Rock Hill",
        "Spartanburg",
        "Summerville",
        "Sumter"
    ],
    "South Dakota": [
        "Rapid City",
        "Sioux Falls"
    ],
    "Tennessee": [
        "Bartlett",
        "Brentwood",
        "Chattanooga",
        "Clarksville",
        "Cleveland",
        "Collierville",
        "Franklin",
        "Germantown",
        "Hendersonville",
        "Jackson",
        "Johnson City",
        "Kingsport",
        "Knoxville",
        "Memphis",
        "Murfreesboro",
        "Nashville-Davidson",
        "Smyrna"
    ],
    "Texas": [
        "Abilene",
        "Allen",
        "Amarillo",
        "Arlington",
        "Austin",
        "Baytown",
        "Beaumont",
        "Bedford",
        "Brownsville",
        "Bryan",
        "Burleson",
        "Carrollton",
        "Cedar Hill",
        "Cedar Park",
        "College Station",
        "Conroe",
        "Coppell",
        "Corpus Christi",
        "Dallas",
        "DeSoto",
        "Denton",
        "Duncanville",
        "Edinburg",
        "El Paso",
        "Euless",
        "Flower Mound",
        "Fort Worth",
        "Friendswood",
        "Frisco",
        "Galveston",
        "Garland",
        "Georgetown",
        "Grand Prairie",
        "Grapevine",
        "Haltom City",
        "Harlingen",
        "Houston",
        "Huntsville",
        "Hurst",
        "Irving",
        "Keller",
        "Killeen",
        "Lancaster",
        "Laredo",
        "League City",
        "Lewisville",
        "Longview",
        "Lubbock",
        "Mansfield",
        "McAllen",
        "McKinney",
        "Mesquite",
        "Midland",
        "Mission",
        "Missouri City",
        "New Braunfels",
        "North Richland Hills",
        "Odessa",
        "Pasadena",
        "Pearland",
        "Pflugerville",
        "Pharr",
        "Plano",
        "Port Arthur",
        "Richardson",
        "Rockwall",
        "Round Rock",
        "Rowlett",
        "San Angelo",
        "San Antonio",
        "San Marcos",
        "Sherman",
        "Sugar Land",
        "Temple",
        "Texarkana",
        "Texas City",
        "The Colony",
        "Tyler",
        "Victoria",
        "Waco",
        "Weslaco",
        "Wichita Falls",
        "Wylie"
    ],
    "Utah": [
        "Bountiful",
        "Draper",
        "Layton",
        "Lehi",
        "Logan",
        "Murray",
        "Ogden",
        "Orem",
        "Provo",
        "Riverton",
        "Roy",
        "Salt Lake City",
        "Sandy",
        "South Jordan",
        "St. George",
        "Taylorsville",
        "West Jordan",
        "West Valley City"
    ],
    "Vermont": [
        "Burlington"
    ],
    "Virginia": [
        "Alexandria",
        "Blacksburg",
        "Charlottesville",
        "Chesapeake",
        "Danville",
        "Hampton",
        "Harrisonburg",
        "Leesburg",
        "Lynchburg",
        "Manassas",
        "Newport News",
        "Norfolk",
        "Portsmouth",
        "Richmond",
        "Roanoke",
        "Suffolk",
        "Virginia Beach"
    ],
    "Washington": [
        "Auburn",
        "Bellevue",
        "Bellingham",
        "Bremerton",
        "Burien",
        "Edmonds",
        "Everett",
        "Federal Way",
        "Kennewick",
        "Kent",
        "Kirkland",
        "Lacey",
        "Lakewood",
        "Marysville",
        "Olympia",
        "Pasco",
        "Puyallup",
        "Redmond",
        "Renton",
        "Richland",
        "Sammamish",
        "Seattle",
        "Shoreline",
        "Spokane Valley",
        "Spokane",
        "Tacoma",
        "Vancouver",
        "Yakima"
    ],
    "West Virginia": [
        "Charleston",
        "Huntington"
    ],
    "Wisconsin": [
        "Appleton",
        "Beloit",
        "Brookfield",
        "Eau Claire",
        "Fond du Lac",
        "Green Bay",
        "Greenfield",
        "Janesville",
        "Kenosha",
        "La Crosse",
        "Madison",
        "Milwaukee",
        "New Berlin",
        "Oshkosh",
        "Racine",
        "Sheboygan",
        "Waukesha",
        "Wausau",
        "Wauwatosa",
        "West Allis"
    ],
    "Wyoming": [
        "Casper",
        "Cheyenne"
    ]
}
]''';
